name: Image Update Check
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Regular Image Updates
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/caddy:builder
          image: technoguyfication/caddy-cloudflare:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Regular Docker Image
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: technoguyfication/caddy-cloudflare:latest
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'

  build-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Alpine Image Updates
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: library/caddy:builder-alpine
          image: technoguyfication/caddy-cloudflare:alpine

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Alpine Docker Image
        uses: docker/build-push-action@v2.6.1
        with:
          context: "${{ github.workspace }}"
          push: true
          tags: technoguyfication/caddy-cloudflare:alpine
          file: "${context}/Dockerfile.alpine"
        if: steps.baseupdatecheck.outputs.needs-updating == 'true'
